language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
    - ./gradlew clean assemble test

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
