language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:

script:
    - ./gradlew clean assemble test --continue

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
